version: '3.8'

services:
  vue-app:
    build:
      context: .  # Répertoire courant contenant le Dockerfile
      dockerfile: Dockerfile  # Spécifie le Dockerfile à utiliser
    image: vue-app-cicd:local  # Nom de l'image à créer
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
