name: Construction du projet et déploiement

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PORT: 5173
  IMAGE_TAG: ${{ secrets.DOCKER_USER }}/vue-app-cicd:latest  # Tag statique pour Docker

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    name: Configuration, tests, et construction du projet
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Configurer Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Exécuter les tests
        run: npm test

      - name: Générer le rapport PDF
        run: |
          node generate-pdf.js --no-sandbox

  build:
    needs: test
    runs-on: ubuntu-latest
    name: Construire et pousser l'image Docker
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/vue-app-cicd:latest .

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pousser l'image Docker sur Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/vue-app-cicd:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Déployer sur Heroku
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer le Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Configurer le stack Heroku sur "container"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku stack:set container --app vue-app-cicd-1

      - name: Connexion à Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Pousser et déployer l'image Docker sur Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:push web --app vue-app-cicd-1
          heroku container:release web --app vue-app-cicd-1

      - name: Verifier les logs
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
            heroku logs --tail --app vue-app-cicd-1

